# VM Hostname Operator Build Script
#
# Builds the VCF9 Supervisor Service (Carvel Package + imgpkg bundle + ytt + kbld).
# Prerequisites: ytt, kbld, imgpkg, docker (or podman), go

NAME           := hostname-operator
VERSION        ?= 1.0.0
REGISTRY       ?= registry.example.com
IMG            ?= $(REGISTRY)/$(NAME):$(VERSION)

# Supervisor Service (VCF9) variables
SERVICE_ID       ?= hostname-operator.vcf.vmware.com
BUNDLE_IMG       ?= $(REGISTRY)/$(NAME)-bundle:$(VERSION)
SUPSVC_SRC       := config/supervisor-service
SUPSVC_BUNDLE    := $(SUPSVC_SRC)/bundle
SUPSVC_PKG_DIR   := $(SUPSVC_SRC)/package
SUPSVC_YAML_OUT  := dist/$(NAME)-supervisorservice-$(VERSION).yaml

BUILD_DIR        := dist
BUNDLE_DIR       := .imgpkg

# Container tool
CONTAINER_TOOL  ?= docker
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec

##@ General

.PHONY: all
all: build

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(MAKEFILE_LIST)

##@ Development

.PHONY: fmt
fmt: ## Run go fmt against code.
	cd supervisor-service && go fmt ./...

.PHONY: vet
vet: ## Run go vet against code.
	cd supervisor-service && go vet ./...

.PHONY: build
build: fmt vet ## Build manager binary.
	cd supervisor-service && CGO_ENABLED=0 go build -o bin/$(NAME) .

##@ Build (Container Image)

.PHONY: docker-build
docker-build: build ## Build docker image with the manager.
	@mkdir -p $(BUILD_DIR)
	cp supervisor-service/bin/$(NAME) $(BUILD_DIR)/
	printf 'FROM gcr.io/distroless/static-debian12:nonroot\nCOPY %s /usr/local/bin/%s\nUSER 65532:65532\nENTRYPOINT ["/usr/local/bin/%s"]\n' "$(NAME)" "$(NAME)" "$(NAME)" > $(BUILD_DIR)/Dockerfile
	$(CONTAINER_TOOL) build -t $(IMG) -f $(BUILD_DIR)/Dockerfile $(BUILD_DIR)
	rm -f $(BUILD_DIR)/$(NAME) $(BUILD_DIR)/Dockerfile

.PHONY: docker-push
docker-push: ## Push docker image with the manager.
	$(CONTAINER_TOOL) push $(IMG)

##@ Supervisor Service (VCF9)

.PHONY: supervisor-crd-sync
supervisor-crd-sync: ## Sync the CRD definition into the Supervisor Service bundle.
	@echo "Syncing CRD -> $(SUPSVC_BUNDLE)/config/002-crd.yaml"
	@{ \
		printf '%s\n' '#! This file is auto-generated by `make supervisor-crd-sync`.'; \
		printf '%s\n' '#! Source: supervisor-service/config/deployment.yml CRD section. Do not edit by hand.'; \
		cat $(SUPSVC_BUNDLE)/config/002-crd.yaml; \
	} > /dev/null
	@echo "  (CRD is maintained directly in bundle/config/002-crd.yaml)"
	@echo "  To regenerate from kubebuilder manifests, use: make manifests && cp config/crd/bases/*.yaml $(SUPSVC_BUNDLE)/config/002-crd.yaml"

.PHONY: supervisor-bundle
supervisor-bundle: supervisor-crd-sync ## Build and push the imgpkg bundle to BUNDLE_IMG. Requires imgpkg + kbld + ytt in PATH.
	@command -v imgpkg >/dev/null 2>&1 || { echo "imgpkg not found. Install Carvel imgpkg."; exit 1; }
	@command -v kbld   >/dev/null 2>&1 || { echo "kbld not found. Install Carvel kbld.";     exit 1; }
	@command -v ytt    >/dev/null 2>&1 || { echo "ytt not found. Install Carvel ytt.";       exit 1; }
	@# Bake the build-time image ref into the bundle so deploy-time ytt renders the same
	@# literal that kbld will later find in the (relocated) ImagesLock.
	@img_repo="$$(printf '%s\n' '$(IMG)' | sed -E 's/:[^:/]+$$//')"; \
	img_tag="$$(printf  '%s\n' '$(IMG)' | sed -E 's#.*:##')";  \
	printf '#@data/values\n#@overlay/match missing_ok=True\n---\nimage:\n  repository: %s\n  tag: "%s"\n' \
	    "$$img_repo" "$$img_tag" > $(SUPSVC_BUNDLE)/config/zz-build-values.yaml; \
	ytt -f $(SUPSVC_BUNDLE)/config \
	    | kbld -f - --imgpkg-lock-output $(SUPSVC_BUNDLE)/.imgpkg/images.yml > /dev/null && \
	imgpkg push -b $(BUNDLE_IMG) -f $(SUPSVC_BUNDLE) --lock-output dist/supervisor-bundle.lock.yml; \
	rc=$$?; rm -f $(SUPSVC_BUNDLE)/config/zz-build-values.yaml; exit $$rc
	@echo "Bundle pushed: $(BUNDLE_IMG)"
	@echo "Lock file:     dist/supervisor-bundle.lock.yml"

.PHONY: supervisor-service-yaml
supervisor-service-yaml: ## Emit the upload-ready Supervisor Service YAML (PackageMetadata + Package) to dist/.
	mkdir -p dist
	@if [ -f dist/supervisor-bundle.lock.yml ]; then \
		digest="$$(awk '/image:/{print $$2; exit}' dist/supervisor-bundle.lock.yml)"; \
		echo "Pinning imgpkgBundle to $$digest"; \
	else \
		digest="$(BUNDLE_IMG)"; \
		echo "WARN: no dist/supervisor-bundle.lock.yml found; pinning to tag $$digest (not a digest)."; \
	fi; \
	{ \
		cat $(SUPSVC_PKG_DIR)/package-metadata.yaml; \
		echo; \
		sed -E "s|image: .*hostname-operator-bundle.*|image: $$digest|" \
			$(SUPSVC_PKG_DIR)/package.yaml; \
	} > $(SUPSVC_YAML_OUT)
	@echo "Wrote $(SUPSVC_YAML_OUT)"
	@echo "Service ID: $(SERVICE_ID)  Version: $(VERSION)"

.PHONY: supervisor-release
supervisor-release: docker-build docker-push supervisor-bundle supervisor-service-yaml ## One-shot: build+push operator image, build+push bundle, emit service YAML.
	@echo
	@echo "Upload $(SUPSVC_YAML_OUT) via vSphere Client -> Workload Management -> Services -> Add New Service."

.PHONY: supervisor-relocate
supervisor-relocate: ## Relocate bundle + referenced images to DEST_REPO (e.g. DEST_REPO=nexus.corp/vcf/$(NAME)-bundle). Source = BUNDLE_IMG.
	@command -v imgpkg >/dev/null 2>&1 || { echo "imgpkg not found. Install Carvel imgpkg."; exit 1; }
	@if [ -z "$(DEST_REPO)" ]; then \
		echo "ERROR: DEST_REPO is required."; \
		echo "  Example: make supervisor-relocate BUNDLE_IMG=$(REGISTRY)/$(NAME)-bundle:$(VERSION) \\"; \
		echo "           DEST_REPO=nexus.corp/vcf/$(NAME)-bundle"; \
		exit 2; \
	fi
	mkdir -p dist
	imgpkg copy -b $(BUNDLE_IMG) --to-repo $(DEST_REPO) --lock-output dist/supervisor-bundle.lock.yml
	@echo
	@echo "Bundle + referenced images copied to $(DEST_REPO)."
	@echo "Next: make supervisor-service-yaml   # pins the Package at the Nexus digest"

.PHONY: supervisor-offline-tar
supervisor-offline-tar: ## Pack bundle + images into a single tar (dist/$(NAME)-airgap-$(VERSION).tar) for transfer to an air-gapped lab. Source = BUNDLE_IMG.
	@command -v imgpkg >/dev/null 2>&1 || { echo "imgpkg not found. Install Carvel imgpkg."; exit 1; }
	mkdir -p dist
	imgpkg copy -b $(BUNDLE_IMG) --to-tar dist/$(NAME)-airgap-$(VERSION).tar
	@echo
	@ls -lh dist/$(NAME)-airgap-$(VERSION).tar

.PHONY: supervisor-offline-import
supervisor-offline-import: ## On the lab side: upload a tar to DEST_REPO and pin the Package YAML. Inputs: TAR=<path>, DEST_REPO=<nexus repo>, SERVICE_YAML=<path>.
	@command -v imgpkg >/dev/null 2>&1 || { echo "imgpkg not found. Install Carvel imgpkg."; exit 1; }
	@if [ -z "$(TAR)" ] || [ -z "$(DEST_REPO)" ] || [ -z "$(SERVICE_YAML)" ]; then \
		echo "ERROR: TAR, DEST_REPO, SERVICE_YAML are required."; \
		echo "  Example: make supervisor-offline-import \\"; \
		echo "           TAR=$(NAME)-airgap-$(VERSION).tar \\"; \
		echo "           DEST_REPO=nexus.corp/vcf/$(NAME)-bundle \\"; \
		echo "           SERVICE_YAML=$(NAME)-supervisorservice-$(VERSION).yaml"; \
		exit 2; \
	fi
	imgpkg copy --tar $(TAR) --to-repo $(DEST_REPO) --lock-output supervisor-bundle.lock.yml
	@digest="$$(awk '/image:/{print $$2; exit}' supervisor-bundle.lock.yml)"; \
	echo "Pinning $(SERVICE_YAML) -> $$digest"; \
	sed -E -i.bak "/imgpkgBundle:/,/image:/ s|image:[[:space:]]+.*-bundle.*|image: $$digest|" $(SERVICE_YAML); \
	rm -f $(SERVICE_YAML).bak
	@echo
	@echo "Done. Upload $(SERVICE_YAML) via vSphere Client -> Workload Management -> Services."

##@ Validation

.PHONY: validate
validate: supervisor-crd-sync ## Validate ytt templates render correctly.
	@command -v ytt >/dev/null 2>&1 || { echo "ytt not found. Install Carvel ytt."; exit 1; }
	@echo "Validating ytt templates..."
	ytt -f $(SUPSVC_BUNDLE)/config --output-files /tmp/$(NAME)-validate
	@echo "Templates validated successfully"
	@rm -rf /tmp/$(NAME)-validate

##@ Cleanup

.PHONY: clean
clean: ## Clean build artifacts.
	rm -rf $(BUILD_DIR) supervisor-service/bin
	rm -f .imgpkg/images.yml